package org.jboss.logging.tools.provisioning.generator;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import javax.tools.DiagnosticCollector;
import javax.tools.JavaCompiler;
import javax.tools.JavaFileObject;
import javax.tools.StandardJavaFileManager;
import javax.tools.StandardLocation;
import javax.tools.ToolProvider;

/**
 * Phase 3: compiles the {@code .java} source files generated by Phase 2 into
 * {@code .class} files using the system Java compiler
 * ({@link ToolProvider#getSystemJavaCompiler()}).
 *
 * <p>A JDK is required at runtime.  If the tool is run on a plain JRE (i.e.
 * {@code getSystemJavaCompiler()} returns {@code null}), an
 * {@link IllegalStateException} is thrown with a clear message.</p>
 */
public class SystemJavacCompiler {

    /**
     * Compiles all {@code .java} files under {@code sourceDir} to {@code .class}
     * files in {@code classOutputDir}.
     *
     * @param sourceDir      root of the generated {@code .java} sources
     * @param classOutputDir directory into which compiled {@code .class} files are written
     * @param classpath      JARs to put on the compilation classpath (source JAR,
     *                       annotations JAR, logging JAR, etc.)
     * @param releaseVersion Java release version integer, e.g. 11, 17, 21.
     *                       Passed as {@code --release N} to the compiler.
     * @param keepSources    if {@code false}, the temp source directory is deleted
     *                       after successful compilation
     * @throws BridgeCompilationException if the compiler reports errors
     * @throws IllegalStateException      if no system Java compiler is available
     */
    public void compile(Path sourceDir, Path classOutputDir, List<Path> classpath,
            int releaseVersion, boolean keepSources) throws Exception {

        JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
        if (compiler == null) {
            throw new IllegalStateException(
                    "No system Java compiler is available. " +
                    "This tool must be run on a JDK, not a plain JRE. " +
                    "Consider using the ECJ variant (BRIDGE-APPROACH-SPEC.md) for JRE-only environments.");
        }

        // Collect .java files
        List<File> javaFiles = Files.walk(sourceDir)
                .filter(p -> p.toString().endsWith(".java"))
                .map(Path::toFile)
                .collect(Collectors.toList());

        if (javaFiles.isEmpty()) {
            return; // nothing to compile
        }

        Files.createDirectories(classOutputDir);

        DiagnosticCollector<JavaFileObject> diagnostics = new DiagnosticCollector<>();
        try (StandardJavaFileManager fm = compiler.getStandardFileManager(
                diagnostics, null, StandardCharsets.UTF_8)) {

            fm.setLocation(StandardLocation.CLASS_OUTPUT, List.of(classOutputDir.toFile()));
            fm.setLocation(StandardLocation.CLASS_PATH,
                    classpath.stream().map(Path::toFile).collect(Collectors.toList()));

            Iterable<? extends JavaFileObject> compilationUnits =
                    fm.getJavaFileObjectsFromFiles(javaFiles);

            List<String> options = List.of("--release", String.valueOf(releaseVersion));

            boolean success = compiler
                    .getTask(null, fm, diagnostics, options, null, compilationUnits)
                    .call();

            if (!success) {
                StringBuilder sb = new StringBuilder("Compilation of generated logger sources failed:\n");
                diagnostics.getDiagnostics().stream()
                        .filter(d -> d.getKind() == javax.tools.Diagnostic.Kind.ERROR)
                        .forEach(d -> sb.append("  ").append(d).append('\n'));
                // Keep sources for inspection on failure
                throw new BridgeCompilationException(sb.toString());
            }
        }

        if (!keepSources) {
            deleteTree(sourceDir);
        }
    }

    // ── Helpers ───────────────────────────────────────────────────────────

    /** Maps a class-file major version to a Java release number. */
    public static int majorVersionToRelease(int majorVersion) {
        // Java 11 = 55, Java 17 = 61, Java 21 = 65
        int release = majorVersion - 44;
        if (release < 8) return 8;   // floor at 8
        return release;
    }

    private void deleteTree(Path root) throws Exception {
        Files.walk(root)
                .sorted(java.util.Comparator.reverseOrder())
                .map(Path::toFile)
                .forEach(File::delete);
    }
}
