<?xml version="1.0" encoding="UTF-8"?>
<!--
    JBoss, Home of Professional Open Source
    Copyright 2015, Red Hat, Inc. and/or its affiliates, and individual
    contributors by the @authors tag. See the copyright.txt in the
    distribution for a full listing of individual contributors.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.wildfly.translations</groupId>
        <artifactId>wildfly-translations-feature-pack-parent</artifactId>
        <version>1.0.0.Final-SNAPSHOT</version>
    </parent>
    <artifactId>wildfly-translations-feature-pack-common</artifactId>
    <packaging>pom</packaging>
    <name>Common content</name>
  
    <description>Common content</description>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.html</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <dependencies>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-ejb3-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-server-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-bootable-jar-runtime-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-cli-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-controller-client-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-controller-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-core-management-subsystem-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-deployment-repository-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-deployment-scanner-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-discovery-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-domain-http-interface-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-domain-management-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-elytron-tool-wrapper-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-elytron-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-embedded-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-host-controller-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-installation-manager-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-io-subsystem-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-jmx-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-logging-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-management-client-content-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-network-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-patching-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-platform-mbean-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-process-controller-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-protocol-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-remoting-subsystem-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-request-controller-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-security-manager-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-threads-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-appclient-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-batch-jberet-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-bean-validation-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-clustering-common-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-clustering-ejb-infinispan-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-clustering-infinispan-extension-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-clustering-jgroups-extension-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-clustering-singleton-extension-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-clustering-singleton-server-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-clustering-web-undertow-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-connector-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-datasources-agroal-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-ee-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-elytron-oidc-client-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-expansion-pack-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-health-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-iiop-openjdk-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-insights-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-jaxrs-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-jdr-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-jpa-hibernate6-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-jpa-hibernatesearch-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-jpa-spi-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-jpa-subsystem-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-jsf-subsystem-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-legacy-keycloak-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-legacy-opentracing-extension-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-mail-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-messaging-activemq-injection-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-messaging-activemq-subsystem-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-metrics-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-microprofile-config-smallrye-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-microprofile-fault-tolerance-smallrye-extension-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-microprofile-health-smallrye-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-microprofile-jwt-smallrye-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-microprofile-lra-coordinator-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-microprofile-lra-participant-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-microprofile-metrics-smallrye-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-microprofile-openapi-smallrye-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-microprofile-reactive-messaging-smallrye-amqp-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-microprofile-reactive-messaging-smallrye-common-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-microprofile-reactive-messaging-smallrye-config-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-microprofile-reactive-messaging-smallrye-extension-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-microprofile-reactive-messaging-smallrye-kafka-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-microprofile-reactive-streams-operators-smallrye-cdi-provider-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-microprofile-reactive-streams-operators-smallrye-extension-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-microprofile-telemetry-smallrye-extension-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-mod-cluster-extension-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-naming-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-observability-micrometer-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-observability-opentelemetry-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-picketlink-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-pojo-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-rts-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-sar-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-security-subsystem-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-system-jmx-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-transactions-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-undertow-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-webservices-server-integration-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-weld-common-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-weld-ejb-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.wildfly.translations</groupId>
            <artifactId>wildfly-xts-translations</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
         <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                       <id>copy-resources</id>
                       <phase>process-resources</phase>
                       <goals>
                           <goal>copy-resources</goal>
                       </goals>
                       <configuration>
                           <outputDirectory>${basedir}/target/resources</outputDirectory>
                           <resources>
                               <resource>
                                   <directory>${basedir}/src/main/resources</directory>
                                   <filtering>false</filtering>
                               </resource>
                           </resources>
                       </configuration>
                   </execution>
                   <execution>
                       <id>filter-artifact-versions</id>
                       <phase>process-resources</phase>
                       <goals>
                           <goal>copy-resources</goal>
                       </goals>
                       <configuration>
                           <outputDirectory>${basedir}/target/resources/resources/wildfly</outputDirectory>
                           <overwrite>true</overwrite>
                           <useDefaultDelimiters>false</useDefaultDelimiters>
                           <delimiters>
                               <delimiter>@</delimiter>
                           </delimiters>
                           <resources>
                               <resource>
                                   <directory>${basedir}/src/main/resources/resources/wildfly</directory>
                                   <includes>
                                       <include>artifact-versions.properties</include>
                                   </includes>
                                   <filtering>true</filtering>
                               </resource>
                           </resources>
                       </configuration>
                   </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
